config/routes.rb
Rails.application.routes.draw do
  resources :borrowers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/borrower.rb
class Borrower < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  def index
    @borrowers = Borrower.all
  end

  def show
  end

  def new
    @borrower = Borrower.new
  end

  def create
    @borrower = Borrower.new(borrower_params)

    if @borrower.save
      redirect_to borrowers_path, notice: "Borrower was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @borrower.update(borrower_params)
      redirect_to borrowers_path, notice: "Borrower was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @borrower.destroy
    redirect_to borrowers_path, notice: "Borrower was successfully deleted."
  end

  private

  def borrower_params
    params.require(:borrower).permit(:name, :email, :address, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% content_for :title, "Editing article" %>

<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Articles" %>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<% content_for :title, "New article" %>

<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/borrowers/_borrowers.html.erb
<table class="table table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @borrowers.each do |borrower| %>
          <tr>
              <td><%= link_to borrower.name, borrower_path(borrower) %></td>
              <td><%= borrower.email %></td>
              <td><%= borrower.address %></td>
              <td><%= borrower.status ? "Active" : "Inactive" %></td>
              <td>
                <%= link_to "Edit",
                            edit_borrower_path(borrower),
                            class: "btn btn-secondary" %>
                <%= button_to "Delete",
                            borrower_path(borrower),
                            method: :delete,
                            class: "btn btn-danger" %>
              </td>
          </tr>
        <% end %>
    </tbody>
</table>

app/views/borrowers/_form.html.erb
<%= form_for @borrower, html: { class: "row g-3" } do |f| %>
    <% if @borrower.errors.any? %>
        <div class="error-message">
        <%= @borrower.errors.full_messages.to_sentence.capitalize %>
        </div>
    <% end %>

    <div class="col-6">
        <label for="name">Name</label>
        <%= f.text_field :name, class: "form-control", placeholder: "John Doe" %>
    </div>
    <div class="col-6">
        <label for="email">Email</label>
        <%= f.text_field :email, class: "form-control", placeholder: "johndoe@example.com" %>
    </div>
    <div class="col-12">
        <label for="address">Address</label>
        <%= f.text_area :address, class: "form-control", placeholder: "1234 Main St" %>
    </div>
    <div class="col-12">
        <div class="form-check">
        <%= f.check_box :status, class: "form-check-input" %>
        <label class="form-check-label" for="gridCheck">
            Active?
        </label>
        </div>
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
<% end %>

app/views/borrowers/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back"), borrowers_path %>

  <div class="header">
    <h1>Edit borrower</h1>
  </div>

  <%= render "form", borrower: @borrower %>
</main>

app/views/borrowers/index.html.erb
<main class="container">
  <div class="header">
    <h1>Borrowers</h1>
    <%= link_to "New borrower",
                new_borrower_path,
                class: "btn btn-primary" %>
  </div>

  <%= render partial: "borrowers", borrowers: @borrowers %>
</main>

app/views/borrowers/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back"), borrowers_path %>

  <div class="header">
    <h1>New borrower</h1>
  </div>

  <%= render "form", borrower: @borrower %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Fintra V3" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>